Add populate-live-files command

diff --git a/bin/installed-to-live b/bin/installed-to-live
--- a/bin/installed-to-live
+++ b/bin/installed-to-live
@@ -39,6 +39,30 @@ PW_FILES="/etc/passwd /etc/shadow /etc/gshadow /etc/group"
 MUNGE_FILES="/etc/slim.conf /etc/lightdm/lightdm.conf"
 BIND_FILES="$PW_FILES $MUNGE_FILES"
 
+LIVE_FILE_LIST="
+/etc/desktop-session/startup
+/etc/fstab
+/etc/init.d/checkfs.sh
+/etc/init.d/cron
+/etc/init.d/debian/*
+/etc/init.d/gpm
+/etc/init.d/hwclock.sh
+/etc/init.d/keyboard-setup
+/etc/init.d/umountfs
+/etc/init.d/sendsigs
+/etc/issue
+/etc/rc.local
+/etc/skel/.fluxbox/menu
+/etc/skel/.icewm/menu
+/etc/skel/.jwm/menu
+/etc/udev/rules.d/90-fstab-automount.rules
+"
+
+GENERAL_LIVE_FILE_LIST="
+/etc/lightdm/lightdm.conf
+/etc/slim.conf
+"
+
 usage() {
     local ret=${1:-0}
 
@@ -52,9 +76,17 @@ This is needed because sometimes we create directories and touch files.
 Commands:
     start               Do the main bind mount and create cleanup.conf
     status              Show status including contents of cleanup.conf
-    general             Make it general purpose
-    passwd              Only make general purpose password/group files
+
+    live-files          bind mount files under $TEMPLATE_DIR/files
+    general-files       bind mount files under $TEMPLATE_DIR/general-files
+    all-files           same as "live-files general-files"
+
+    passwd              Make general purpose password/group files
+
     add=<dir1,dir2,..>  Add files from the dirs template
+
+    general             Same as "all-files passwd"
+
     cleanup             Clean up all that we did
 
     empty=<dir1,dir2,...>
@@ -67,6 +99,10 @@ Commands:
     version-file[=<title>]
                         Create a standard linuxfs.ver file and bind mount it
                         at the appropriate location: $VERSION_FILE
+
+    populate-live-files=<from-dir>
+                        Populate the $TEMPLATE_DIR with files extracted from
+                        <from-dir>.  This is usually a mounted linuxfs file.
 Options:
 
     -b --bind-root=<dir>       The root of the new fs.   Default: $BIND_ROOT
@@ -167,7 +203,10 @@ main() {
               start) do_start         $CONF_FILE $WORK_DIR             ;;
              status) do_status        $CONF_FILE                       ;;
               add=*) do_add           $CONF_FILE $WORK_DIR "$val"      ;;
-            general) do_general       $CONF_FILE                       ;;
+         live-files) do_live_files    $CONF_FILE $WORK_DIR             ;;
+      general-files) do_general_files $CONF_FILE $WORK_DIR             ;;
+          all-files) do_all_files     $CONF_FILE $WORK_DIR             ;;
+            general) do_general       $CONF_FILE $WORK_DIR             ;;
              passwd) do_passwd        $CONF_FILE                       ;;
             cleanup) do_cleanup       $CONF_FILE $WORK_DIR             ;;
             empty=*) do_empty         $CONF_FILE $WORK_DIR "$val"      ;;
@@ -175,8 +214,38 @@ main() {
      version-file=*) do_version_file  $CONF_FILE $WORK_DIR "$val"      ;;
           exclude=*) do_exclude       "$val" "$@" ; exit 0             ;;
             exclude) do_exclude       ""     "$@" ; exit 0             ;;
+
+ populate-live-files=*) do_populate_live "$val"                        ;;
+
                   *) fatal "Unexpected command: $cmd."
         esac
+    done
+}
+
+do_populate_live() {
+    local from_dir=$1
+    test -d "$from_dir" || fatal "$from is not a directory"
+    copy_files "$from_dir" "$LIVE_FILE_LIST"         "$TEMPLATE_DIR/files"
+    copy_files "$from_dir" "$GENERAL_LIVE_FILE_LIST" "$TEMPLATE_DIR/general-files"
+}
+
+copy_files() {
+    local from_dir=$1 files=$2 to_dir=$3
+    [ -z "$to_dir" -o -n "${to_dir##*[a-zA-Z]*}" ] && fatal "suspicious to-dir: $to_dir"
+
+    pretend rm -rf $to_dir
+    pretend mkdir -p $to_dir
+    local list=$(echo "$files" | grep -v "^\s*#\s*" | sed 's/\s*#.*//' \
+        | grep "^/" | sed "s=^=$from_dir=")
+
+    local file
+    for file in $list; do
+        test -e $file || continue
+        local dest_file=${file#$from_dir}
+        local dest=$to_dir$dest_file
+        local dist_dir=$(dirname $dest)
+        test -d $dest_dir || pretend mkdir -p $dest_dir
+        pretend cp -a $file $dest
     done
 }
 
@@ -224,12 +293,11 @@ do_exclude() {
 
     case $ecnt in
         0) exit 0;;
-        1) fatal "One missing exclude file" ;;
-        *) fatal "$ecnt missing exclude files" ;;
+        1) fatal "One missing exclude file"    ; exit 2 ;;
+        *) fatal "$ecnt missing exclude files" ; exit 2 ;;
     esac
 
-    exit 2
-
+    exit 3
 }
 
 do_start() {
@@ -238,7 +306,7 @@ do_start() {
     [ -z "$FORCE" -a -e "$work_dir" ] && fatal "Work dir $work_dir exists.  Use --Force to delete it"
     test -e $work_dir && rm -rf $work_dir
 
-    mkdir -p $BIND_ROOT
+    mkdir -p $BIND_ROOT || fatal "Could not make bind root directory $BIND_ROOT"
     if mountpoint -q $BIND_ROOT &>/dev/null; then
 
         [ -z "$FORCE" ] && fatal "bind-root: $BIND_ROOT is already a mount point"
@@ -307,7 +375,6 @@ do_status() {
     exit 0
 }
 
-
 do_passwd() {
     local conf_file=$1
     read_conf_file $conf_file
@@ -317,16 +384,47 @@ do_passwd() {
     write_conf_file $CONF_FILE
 }
 
+do_live_files() {
+    local conf_file=$1  work_dir=$2
+    _do_files $conf_file $work_dir $TEMPLATE_DIR/files $work_dir/live-files
+}
+
+do_general_files() {
+    local conf_file=$1  work_dir=$2
+    _do_files $conf_file $work_dir $TEMPLATE_DIR/general-files $work_dir/general-files
+}
+
+_do_files() {
+    local conf_file=$1 work_dir=$2 from=$3 temp=$4
+    read_conf_file $conf_file
+    test -d $from || fatal "Directory $from does not exist"
+    mkdir -p $temp || fatal "Could not mkdir -p $temp"
+    cp -r $from/* $temp/ 2>/dev/null
+    bind_mount_template "$temp"  "$BIND_ROOT" "$REAL_ROOT"
+
+    write_conf_file $CONF_FILE
+}
+
+
+do_all_files() {
+    do_live_files "$@"
+    do_general_files "$@"
+}
 
 do_general() {
-    local conf_file=$1
-    read_conf_file $conf_file
+    local conf_file=$1  work_dir=$2
 
-    bind_mount_template "$TEMPLATE_DIR"   "$BIND_ROOT" "$REAL_ROOT"
+    do_all_files $conf_file $work_dir
+
+    do_passwd $conf_file
+
+    #read_conf_file $conf_file
+
+    #bind_mount_template "$TEMPLATE_DIR"   "$BIND_ROOT" "$REAL_ROOT"
     #bind_empty_dirs     "$WORK_DIR/empty" "$BIND_ROOT" "$REAL_ROOT"
     #munge_files         "$TEMPLATE_DIR"   "$BIND_ROOT" "$WORK_DIR" "$USER_PW" "$ROOT_PW"
 
-    write_conf_file $CONF_FILE
+    #write_conf_file $CONF_FILE
 }
 
 do_cleanup() {
@@ -371,6 +469,7 @@ bind_mount_template() {
         local base=${file#$template_dir}
         local targ=$bind_root$base
         touch_file "$targ" "$real_root$base"
+        is_mounted $targ && error "File $targ is already mounted"
         pretend mount --bind $file $targ
     done <<Bind_Template
 $(find $template_dir -type f)
@@ -485,6 +584,22 @@ munge_files() {
         pretend sed -i -r -e "s/:$user_1000(,|$)/:$def_user/" -e "s/,$user_1000(,|$)/,$def_user\1/" $grp_files
     fi
 
+    set_password $user_pw $bind_from
+    set_password $root_pw $bind_from
+
+    # Bind mount files under $bind_from/
+    for file in $BIND_FILES; do
+        local from=$bind_from$file
+        local to=$bind_root$file
+        test -e $from || continue
+        is_mounted $to && error "File $to is already mounted"
+        pretend mount --bind $from $to
+    done
+}
+
+do_xorg_login() {
+    #FIXME!
+    exit 10
     do_sed $bind_from/etc/slim.conf \
         -e "s/^(\s#)*(default_user +).*/\2$def_user/" \
         -e "/xserver_arguments/ s/ -dpi\s+[0-9]+//"   \
@@ -493,15 +608,6 @@ munge_files() {
     do_sed $bind_from/etc/lightdm/lightdm.conf \
         -e "/autologin-user=demo/ s/^#+//" \
         -e "/xserver-command/ s/ -dpi [0-9]+//"
-
-    set_password $user_pw $bind_from
-    set_password $root_pw $bind_from
-
-    # Bind mount files under $bind_from/
-    for file in $BIND_FILES; do
-        test -e $bind_root$file || continue
-        pretend mount --bind $bind_from$file $bind_root$file
-    done
 }
 
 do_sed() {
@@ -579,6 +685,11 @@ error() {
     echo -e "$ME Error: $msg" >&2
 }
 
+is_mounted() {
+    local file=$1
+    cut -d" " -f2 /proc/mounts | grep -q "^$file$"
+    return $?
+}
 
 pretend() {
     [ "$PRETEND" -o "$VERBOSE" ] && echo "$@"
