Allow multi-line fatal() and error() messages

diff --git a/bin/installed-to-live b/bin/installed-to-live
--- a/bin/installed-to-live
+++ b/bin/installed-to-live
@@ -470,21 +470,23 @@ read_conf_file() {
 
     if ! test -r $conf_file; then
         [ "$force" ] || fatal "Could not find config file $conf_file"
-        return
+        return 1
     fi
 
     . $conf_file
+
+    return 0
 }
 
 fatal() {
     local msg=$1  ret=${2:-2}
-    echo "$ME Fatal Error: $msg" >&2
+    echo -e "$ME Fatal Error: $msg" >&2
     exit $ret
 }
 
 error() {
     local msg=$1
-    echo "$ME Error: $msg" >&2
+    echo -e "$ME Error: $msg" >&2
 }
 
 
